// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package routes

import (
	"cp_tracker/db"
	"cp_tracker/user/controllers"
	"cp_tracker/user/services"
	"go.mongodb.org/mongo-driver/mongo"
)

// Injectors from wire.go:

func InitializeApp() (App, error) {
	database, err := db.ProvideMongoDB()
	if err != nil {
		return App{}, err
	}
	userService, err := services.NewUserService(database)
	if err != nil {
		return App{}, err
	}
	userController := controllers.NewUserController(userService)
	app := App{
		MongoDB:        database,
		UserService:    userService,
		UserController: userController,
	}
	return app, nil
}

// wire.go:

type App struct {
	MongoDB        *mongo.Database
	UserService    *services.UserService
	UserController *controllers.UserController
}
